//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleService
    {
        public int IDService { get; set; }
        public int IDSeller { get; set; }
        public int IDCustomer { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Service Service { get; set; }
    }
}
