//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer.Entity
{
	using System;
	using System.Collections.Generic;

	public partial class Seller
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Seller()
		{
			this.SaleAccessories = new HashSet<SaleAccessory>();
			this.SaleItems = new HashSet<SaleItem>();
			this.SaleServices = new HashSet<SaleService>();
		}

		public int ID { get; set; }
		public string Surname { get; set; }
		public string Firstname { get; set; }
		public string Patronymic { get; set; }
		public string Initials
		{
			get
			{
				if (string.IsNullOrWhiteSpace(Firstname) && string.IsNullOrWhiteSpace(Patronymic)) return $"{Surname}";
				else if (string.IsNullOrWhiteSpace(Patronymic)) return $"{Surname} {Firstname[0]}.";
				else return $"{Surname} {Firstname[0]}. {Patronymic[0]}.";
			}
		}

		public string Fullname
		{
			get => $"{Surname} {Firstname} {Patronymic}";
		}

		public string Phone { get; set; }
		public string Email { get; set; }
		public int UserID { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<SaleAccessory> SaleAccessories { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<SaleItem> SaleItems { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<SaleService> SaleServices { get; set; }
		public virtual User User { get; set; }
	}
}
